import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>CSU | Open Services</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-2xl text-red-500'>Hello World!</h1>
    </div>
  );
}
