import React from 'react';
import Navbar from '../navbar';
import Head from 'next/head';

export default function MainLayout({ children }) {
  return (
    <div>
      <Head>
        <title>CSU | Open Services</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      {children}
    </div>
  );
}
